filedir<-"C://Users//reza//project//household_power_consumption.txt"
dataa <- read.table(filedir,  sep=";",header=TRUE,dec=".", stringsAsFactors=FALSE)
dataa$Date <- as.Date(dataa$Date, format="%d/%m/%Y")
data <- subset(dataa, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(dataa)
datetime <- paste(as.Date(data$Date), data$Time)
data$Datetime <- as.POSIXct(datetime)
globalActivePower <- as.numeric(data$Global_active_power)
hist(globalActivePower, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")
dev.copy(png, file="plot1.png", height=480, width=480)
dev.off()
